import type { AITaskKind, AITaskResult, AITaskResultFile } from "@/lib/ai/types"

/**
 * Classify a prompt into a task kind + human title.
 * Fully deterministic — pattern matches the leading verb only.
 */
export function classifyPrompt(prompt: string): { kind: AITaskKind; title: string } {
  const trimmed = prompt.trim()
  const firstLine = trimmed.split("\n")[0] ?? ""
  const title =
    firstLine.length > 72 ? `${firstLine.slice(0, 69)}...` : firstLine || "Untitled task"
  const lower = trimmed.toLowerCase()

  if (/^(scaffold|create|initialize|bootstrap|set up|new)\b/.test(lower)) {
    return { kind: "scaffold", title }
  }
  if (/^(refactor|rename|restructure|move|extract)\b/.test(lower)) {
    return { kind: "refactor", title }
  }
  if (/^(explain|describe|what|how|why)\b/.test(lower)) {
    return { kind: "explain", title }
  }
  return { kind: "edit", title }
}

function codeBlock(path: string, language: string, content: string): AITaskResultFile {
  return { path, language, content }
}

/**
 * Produce a deterministic AITaskResult from (prompt, projectName).
 * No randomness, no network, no model calls. Output is stable for the same input.
 */
export function generateResult(prompt: string, projectName: string): AITaskResult {
  const cleaned = prompt.trim()
  const lower = cleaned.toLowerCase()
  const { kind } = classifyPrompt(cleaned)

  const files: AITaskResultFile[] = []

  files.push(
    codeBlock(
      "README.md",
      "markdown",
      "# " +
        projectName +
        "\n\n" +
        cleaned +
        "\n\n## Notes\n\n- Generated by the UDD AI task loop.\n- This output is a plan; no files have been written to the project yet.\n",
    ),
  )

  if (lower.includes("landing") || lower.includes("hero") || lower.includes("home page")) {
    files.push(
      codeBlock(
        "app/page.tsx",
        "tsx",
        'export default function Page() {\n  return (\n    <main className="flex min-h-screen items-center justify-center bg-background text-foreground">\n      <section className="flex max-w-xl flex-col gap-4 px-6 text-center">\n        <h1 className="text-4xl font-semibold tracking-tight text-balance">' +
          projectName +
          '</h1>\n        <p className="text-sm text-muted-foreground leading-relaxed">\n          ' +
          cleaned.replace(/`/g, "'") +
          "\n        </p>\n      </section>\n    </main>\n  )\n}\n",
      ),
    )
  } else if (lower.includes("api") || lower.includes("route") || lower.includes("endpoint")) {
    files.push(
      codeBlock(
        "app/api/hello/route.ts",
        "ts",
        'export async function GET() {\n  return Response.json({\n    project: "' +
          projectName +
          '",\n    status: "ok",\n  })\n}\n',
      ),
    )
  } else if (kind === "refactor") {
    files.push(
      codeBlock(
        "PLAN.md",
        "markdown",
        "# Refactor plan\n\nTarget: " +
          projectName +
          "\n\n## Steps\n\n1. Identify affected modules.\n2. Extract shared logic into `lib/`.\n3. Update callers and run type-check.\n",
      ),
    )
  } else if (kind === "explain") {
    files.push(
      codeBlock(
        "ANSWER.md",
        "markdown",
        "# Answer\n\n**Question:** " +
          cleaned +
          "\n\nThis is a simulated explanation. When a real AI provider is wired up it will\nproduce a grounded answer using the project files as context.\n",
      ),
    )
  } else {
    files.push(
      codeBlock(
        "notes.md",
        "markdown",
        "# Planning notes\n\n**Prompt**\n\n" +
          cleaned +
          "\n\n**Proposed next steps**\n\n- Break the request into concrete file changes.\n- Confirm the target surface area with the user.\n- Apply changes in the `Files` tab once orchestration lands.\n",
      ),
    )
  }

  const summary =
    kind === "scaffold"
      ? "Drafted " +
        files.length +
        " file" +
        (files.length === 1 ? "" : "s") +
        " for the initial scaffold."
      : kind === "refactor"
        ? "Outlined a " + files.length + "-file refactor plan."
        : kind === "explain"
          ? "Answered the question in a markdown file."
          : "Prepared " +
            files.length +
            " file" +
            (files.length === 1 ? "" : "s") +
            " based on the prompt."

  return { type: "code_change", files, summary }
}
